export const kpiColors = {
  blue: '#2563EB',
  blueLight: '#EFF6FF',
  blueBorder: '#BFDBFE',
  green: '#16A34A',
  greenBright: '#22C55E',
  greenLight: '#DCFCE7',
  orange: '#F59E0B',
  orangeLight: '#FEF3C7',
  purple: '#8B5CF6',
  purpleDark: '#7C3AED',
  purpleLight: '#F3E8FF',
  red: '#EF4444',
  redLight: '#FEE2E2',
  slate: '#64748B',
  slateDark: '#0F172A',
  slateLight: '#F1F5F9',
  border: '#E7ECF3',
  background: '#F8FAFC',
  cardBg: '#FFFFFF',
} as const;
